### ISSUE TITLE
(김민준) 겜프프로젝트 과정평가용(방문기록)

### ISSUE THREAD

**Issue by GGMinwok** [KMJ1324/GameProgrammingDiary#1]
5/26 깃허브 접속확인

**Comment by KMJ1324** [comment]
접속확인

**Comment by GGMinwok** [comment]
일지 확인하고 갑니다. 꼼꼼하게 잘 작성했어요. 칭찬! 
기록할 때 당일 기록 + 그 전까지 무엇을 했는지 한 주의 과정도 따로 해주면 좋을 듯...
해당 날짜 예를들어 6/9 수업이면 6/8까지의 작업내용/6/9 당일 1-3교시 작업내용을 구분하여 기록해주기!!

**Comment by KMJ1324** [comment]
넴 
참고해서 작성할게요!!

**Comment by GGMinwok** [comment]
6/22 작업확인함

**Comment by GGMinwok** [comment]
마지막 확인완료
작업과정 기록 남겨두세요. 
(2022년 동안 삭제 금지)
